### ISSUE TITLE
你好，监听既然是靠MQTT，那这个项目里的MQTT如何使用

### ISSUE THREAD

**Issue by qcotto** [oldweipro/hik-dev#10]
你好，监听既然是靠MQTT，那这个项目里的MQTT如何使用，我看application.yml文件里面也没有相关的MQTT配置，MqttConfig.java里面也没有什么服务器用户名什么的配置。还有这个MQTT是要DOCKER部暑第三方MQTT还是，如果只生成JAR包，然后运行JAR包，里面自己就有MQTT？如果是JAR包不带MQTT，那么怎么配置MQTT的服务器连接信息？

**Comment by oldweipro** [comment]
一、你可以调用`GET` `/mqtt/init`接口传入参数`broker` `subTopic` `pubTopic` `qos` `username` `password`，本项目只是一个demo，你可以根据自己的业务修改mqtt配置入口（可以写到yaml配置文件中，ApplicationRunner可以在程序启动时做一些事情）。

二、项目中使用
```
<dependency>
    <groupId>org.eclipse.paho</groupId>
        <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
    <version>1.2.5</version>
</dependency>
```
作为项目中发送接收mqtt的客户端，具体代码在`hik-dev/src/main/java/com/oldwei/hikdev/mqtt/MqttConnectClient.java`中

三、请自行搭建mqtt服务
我常用的是emqx，也可以选择其他mqtt server
```
https://www.emqx.io/downloads
```

**Comment by qcotto** [comment]
> 一、你可以调用`GET` `/mqtt/init`接口传入参数`broker` `subTopic` `pubTopic` `qos` `username` `password`，本项目只是一个demo，你可以根据自己的业务修改mqtt配置入口（可以写到yaml配置文件中，ApplicationRunner可以在程序启动时做一些事情）。
> 
> 二、项目中使用
> 
> ```
> <dependency>
>     <groupId>org.eclipse.paho</groupId>
>         <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
>     <version>1.2.5</version>
> </dependency>
> ```
> 
> 作为项目中发送接收mqtt的客户端，具体代码在`hik-dev/src/main/java/com/oldwei/hikdev/mqtt/MqttConnectClient.java`中
> 
> 三、请自行搭建mqtt服务 我常用的是emqx，也可以选择其他mqtt server
> 
> ```
> https://www.emqx.io/downloads
> ```

谢谢，意思是里面是带了MQTT Client，并且会自动接收门禁或者摄像头的事件，只需要输入MQTT的服务器信息和账号密码等信息，然后会自动上传MQTT 服务器是这意思吗？还是上传事件过程要自己编写？
