### ISSUE TITLE
这个使用说明能详细点吗？

### ISSUE THREAD

**Issue by qcotto** [oldweipro/hik-dev#9]
几个配置文件的位置在哪里，比如MQTT，还有配置JSON

还有好像缺少，查询门禁记录的API，就是查询人员刷脸或者刷卡通过的历史记录，报警记录

能否支持报警上传功能，就是报警监听

**Comment by qcotto** [comment]
target目录是什么目录

**Comment by qcotto** [comment]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 12 21:26:45 CST 2023
There was an unexpected error (type=Not Found, status=404).

**Comment by qcotto** [comment]
这个接口总是获取不到正确的数据
/api/access/people/searchPeoples/192.168.30.20?employeeNos=11&queryRequest=0

**Comment by oldweipro** [comment]
最近手头没有设备了，有些接口错误我也不好说问题在哪了。

> 这个接口总是获取不到正确的数据 /api/access/people/searchPeoples/192.168.30.20?employeeNos=11&queryRequest=0

**Comment by oldweipro** [comment]
> 几个配置文件的位置在哪里，比如MQTT，还有配置JSON
> 
> 还有好像缺少，查询门禁记录的API，就是查询人员刷脸或者刷卡通过的历史记录，报警记录
> 
> 能否支持报警上传功能，就是报警监听

文档待补齐，报警监听是靠mqtt订阅发布的，接收到门禁事件记录到业务数据库中。

**Comment by qcotto** [comment]
> > 几个配置文件的位置在哪里，比如MQTT，还有配置JSON
> > 还有好像缺少，查询门禁记录的API，就是查询人员刷脸或者刷卡通过的历史记录，报警记录
> > 能否支持报警上传功能，就是报警监听
> 
> 文档待补齐，报警监听是靠mqtt订阅发布的，接收到门禁事件记录到业务数据库中。

你好，监听既然是靠MQTT，那这个项目里的MQTT如何使用，我看application.yml文件里面也没有相关的MQTT配置，MqttConfig.java里面也没有什么服务器用户名什么的配置。还有这个MQTT是要DOCKER部暑第三方MQTT还是，生成JAR包后运行JAR包，里面自己就有MQTT？如果是JAR包不带MQTT，那么怎么配置MQTT的连接信息？
